apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appserver.service.name }}
spec:
  type: {{ .Values.appserver.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.appserver.image.targetPort }}
      nodePort: {{ .Values.appserver.image.nodePort }}
  selector:
    server: {{ .Values.appserver.name }}